# Info for usage behind reverse proxy
# https://github.com/zulip/docker-zulip/wiki/Proxying-via-nginx-on-host-machine

services:
  database:
    image: "zulip/zulip-postgresql:14"
    restart: unless-stopped
    environment:
      POSTGRES_DB: "zulip"
      POSTGRES_USER: "zulip"
      # Note that you need to do a manual `ALTER ROLE` query if you
      # change this on a system after booting the postgres container
      # the first time on a host.  Instructions are available in README.md.
      POSTGRES_PASSWORD: '${SERVICE_PASSWORD_64_POSTGRES}'
    volumes:
      - "postgresql-14:/var/lib/postgresql/data:rw"
  memcached:
    image: "memcached:alpine"
    restart: unless-stopped
    command:
      - "sh"
      - "-euc"
      - |
        echo 'mech_list: plain' > "$$SASL_CONF_PATH"
        echo "zulip@$$HOSTNAME:$$MEMCACHED_PASSWORD" > "$$MEMCACHED_SASL_PWDB"
        echo "zulip@localhost:$$MEMCACHED_PASSWORD" >> "$$MEMCACHED_SASL_PWDB"
        exec memcached -S
    environment:
      SASL_CONF_PATH: "/home/memcache/memcached.conf"
      MEMCACHED_SASL_PWDB: "/home/memcache/memcached-sasl-db"
      MEMCACHED_PASSWORD: '${SERVICE_PASSWORD_64_MEMCACHED}'
  rabbitmq:
    image: "rabbitmq:3.12.14"
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: "zulip"
      RABBITMQ_DEFAULT_PASS: '${SERVICE_PASSWORD_64_RABBITMQ}'
    volumes:
      - "rabbitmq:/var/lib/rabbitmq:rw"
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    command:
      - "sh"
      - "-euc"
      - |
        echo "requirepass '$$REDIS_PASSWORD'" > /etc/redis.conf
        exec redis-server /etc/redis.conf
    environment:
      REDIS_PASSWORD: '${SERVICE_PASSWORD_64_REDIS}'
    volumes:
      - "redis:/data:rw"
  zulip:
    image: "zulip/docker-zulip:9.2-0"
    restart: unless-stopped
    build:
      context: .
      args:
        # Change these if you want to build zulip from a different repo/branch
        ZULIP_GIT_URL: https://github.com/zulip/zulip.git
        ZULIP_GIT_REF: "9.2"
        # Set this up if you plan to use your own CA certificate bundle for building
        # CUSTOM_CA_CERTIFICATES:
    #ports:
    #  - "80:80"
    #  - "443:443"
    environment:
      # See https://github.com/zulip/docker-zulip#configuration for
      # details on this section and how to discover the many
      # additional settings that are supported here.
      DB_HOST: "database"
      DB_HOST_PORT: "5432"
      DB_USER: "zulip"
      SSL_CERTIFICATE_GENERATION: "self-signed"
      SETTING_MEMCACHED_LOCATION: "memcached:11211"
      SETTING_RABBITMQ_HOST: "rabbitmq"
      SETTING_REDIS_HOST: "redis"
      DISABLE_HTTPS: true
      SECRETS_email_password: '${EMAIL_HOST_PASSWORD}'
      # These should match RABBITMQ_DEFAULT_PASS, POSTGRES_PASSWORD,
      # MEMCACHED_PASSWORD, and REDIS_PASSWORD above.
      SECRETS_rabbitmq_password: '${SERVICE_PASSWORD_64_RABBITMQ}'
      SECRETS_postgres_password: '${SERVICE_PASSWORD_64_POSTGRES}'
      SECRETS_memcached_password: '${SERVICE_PASSWORD_64_MEMCACHED}'
      SECRETS_redis_password: '${SERVICE_PASSWORD_64_REDIS}'
      SECRETS_secret_key: '${SERVICE_PASSWORD_64_SECRET_KEY}'
      SETTING_EXTERNAL_HOST: '${EXTERNAL_HOST}'
      SETTING_ZULIP_ADMINISTRATOR: '${ADMINISTRATOR_EMAIL}'
      SETTING_EMAIL_HOST: '${EMAIL_HOST}' # e.g. smtp.example.com
      SETTING_EMAIL_HOST_USER: '${EMAIL_HOST_USER}'
      SETTING_EMAIL_PORT: '${EMAIL_PORT}'
      # It seems that the email server needs to use ssl or tls and can't be used without it
      SETTING_EMAIL_USE_SSL: '${EMAIL_USE_SSL}'
      SETTING_EMAIL_USE_TLS: '${EMAIL_USE_TLS}'
      ZULIP_AUTH_BACKENDS: "EmailAuthBackend"
      # Uncomment this when configuring the mobile push notifications service
      # SETTING_ZULIP_SERVICE_PUSH_NOTIFICATIONS: "True"
      # SETTING_ZULIP_SERVICE_SUBMIT_USAGE_STATISTICS: "True"

      # If you're using a reverse proxy, you'll want to provide the
      # comma-separated set of IP addresses to trust here.
      LOADBALANCER_IPS: '${DOCKER_IP_NETWORK}'
    volumes:
      - "/data/zulip:/data:rw"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1048576
volumes:
  zulip:
  postgresql-14:
  rabbitmq:
  redis:
